{
 "title": "New dashboard",
 "description": "add RPM panel",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Networking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "1/m" } },
   "targets": [
    { "expr": "rate(gin_requests_total[1m])", "legendFormat": "Requests Per Minute" }
   ]
  },
  {
   "title": "Errors Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "rate(gin_requests_total{code=~\"5..\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(gin_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "Latency P95"
    }
   ]
  },
  { "title": "Server health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "Allocated memory" }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "# goroutines" }
   ]
  },
  {
   "title": "Garbage Collector",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_count[$__rate_interval])",
     "legendFormat": "GC Duration"
    }
   ]
  }
 ]
}